services:
  maintenance-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_MAINTENANCE_TITLE: "Sedang Dalam Perbaikan"
        NEXT_PUBLIC_MAINTENANCE_SUBTITLE: "Kami sedang melakukan pemeliharaan sistem untuk meningkatkan layanan"
        NEXT_PUBLIC_MAINTENANCE_WHAT: "Sistem sedang dalam proses pembaruan untuk meningkatkan performa dan keamanan. Mohon bersabar menunggu hingga proses selesai."
        NEXT_PUBLIC_MAINTENANCE_WHEN: "Kami akan kembali online secepatnya. Silakan coba refresh halaman ini secara berkala."
        NEXT_PUBLIC_MAINTENANCE_ESTIMATED_TIME: "Estimasi selesai: 2 jam lagi"
        NEXT_PUBLIC_MAINTENANCE_CONTACT: "Untuk informasi lebih lanjut hubungi: general.official32@gmail.com"
        NEXT_PUBLIC_MAINTENANCE_END_TIME: "2026-09-23T10:48:00"
        NEXT_PUBLIC_MAINTENANCE_EMAIL: "it@bkpsdm.pesisirselatankab.go.id"
    container_name: maintenance-app
    ports:
      - "3099:3000"
    environment:
      - NODE_ENV=production
    networks:
      - proxy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://127.0.0.1:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  proxy-network:
    external: true
